### ISSUE TITLE
Could you please provide the information how to use dascript with 3D (opengl or BGFX). 

### ISSUE THREAD

**Issue by lvdpower** [imp5imp5/dasbox#15]
Could you please provide the information how to use dascript with 3D (opengl or BGFX). I was trying to enable in cmake option BGFX, but with this I am getting error - [ 27%] Built target daScript
[ 27%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/opengl_boost.das -> /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
[ 27%] Built target dasImguiOpenGL_AOT_opengl_boost.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_demo.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_demo.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_opengl2.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_opengl2.das_aot
make[2]: *** No rule to make target ../modules/dasImgui/imgui/imgui_boost.das', needed by ../modules/dasImgui/imgui/_aot_generated/dasImguiOpenGL_AOT_imgui_boost.das.cpp'. Stop.
make[1]: *** [CMakeFiles/dasImguiOpenGL_AOT_imgui_boost.das_aot.dir/all] Error 2
make: *** [all] Error 2 . I have installed BGFX library in system via build this https://github.com/bkaradzic/bgfx.cmake and sudo make install , but this did not help. I also was trying with DASBOX, but iot seems it does not provide 3d GAPI.. (only 2d may be I am wrong... I do not know) Thank you and for any who can help. [timur123@gmail.com](mailto:timur123@gmail.com) Timur

**Comment by imp5imp5** [comment]
Sorry for the late reply.
dasbox does not support 3d graphics yet, but here is an easy way to use 3d (OpenGL) with daScript:
```
git clone --recurse-submodules git@github.com:GaijinEntertainment/daScript.git

cd daScript
mkdir build
cd build

rem Visual Studio 2017 Express
cmake -G "Visual Studio 15 Win64" ..

cmake --build . --target daScript --config Release
cd ..

bin\Release\daScript modules/dasGlfw/framework/example_app.das
```
